# Generated by Django 3.2.9 on 2021-12-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
    ]
