# Generated by Django 3.2.9 on 2021-12-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_translate_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
    ]
