# Generated by Django 3.2.9 on 2021-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_translate_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translate',
            old_name='file',
            new_name='filesend',
        ),
        migrations.AddField(
            model_name='translate',
            name='filerisive',
            field=models.FileField(max_length=300, null=True, upload_to='files', verbose_name='فایل'),
        ),
    ]
