# Generated by Django 3.2.9 on 2021-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_auto_20211215_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='تمام شده'),
        ),
    ]
