# Generated by Django 3.2.9 on 2021-12-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_translate_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='status',
        ),
    ]
