# Generated by Django 3.2.9 on 2021-12-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0006_remove_translate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='type',
            field=models.CharField(choices=[('t', 'ترجمه'), ('e', 'ویراستاری'), ('pt', 'ترجمه تخصصی')], default='t', max_length=2, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate', to=settings.AUTH_USER_MODEL, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='filerisive',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='files', verbose_name='فایل'),
        ),
    ]
